/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as PanelRouteImport } from './_panel'
import { Route as LoginRouteImport } from './login'
import { Route as RestablecerPasswordRouteImport } from './restablecer-password'
import { Route as SolicitarRouteImport } from './solicitar'
import { Route as PanelIndexRouteImport } from './_panel/index'
import { Route as PanelAdminsRouteImport } from './_panel/admins'
import { Route as PanelAuditoriaRouteImport } from './_panel/auditoria'
import { Route as PanelEmpresasRouteImport } from './_panel/empresas'
import { Route as PanelFacturasRouteImport } from './_panel/facturas'
import { Route as PanelPlanesRouteImport } from './_panel/planes'
import { Route as PanelSolicitudesRouteImport } from './_panel/solicitudes'
import { Route as PanelTelegramRouteImport } from './_panel/telegram'
import { Route as PanelEmpresasIndexRouteImport } from './_panel/empresas.index'
import { Route as PanelEmpresasIdRouteImport } from './_panel/empresas.$id'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerPasswordRoute = RestablecerPasswordRouteImport.update({
  id: '/restablecer-password',
  path: '/restablecer-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminsRoute = PanelAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAuditoriaRoute = PanelAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEmpresasRoute = PanelEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFacturasRoute = PanelFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPlanesRoute = PanelPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSolicitudesRoute = PanelSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTelegramRoute = PanelTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEmpresasIndexRoute = PanelEmpresasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelEmpresasRoute,
} as any)
const PanelEmpresasIdRoute = PanelEmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/login': typeof LoginRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/solicitar': typeof SolicitarRoute
  '/admins': typeof PanelAdminsRoute
  '/auditoria': typeof PanelAuditoriaRoute
  '/empresas': typeof PanelEmpresasRouteWithChildren
  '/facturas': typeof PanelFacturasRoute
  '/planes': typeof PanelPlanesRoute
  '/solicitudes': typeof PanelSolicitudesRoute
  '/telegram': typeof PanelTelegramRoute
  '/empresas/$id': typeof PanelEmpresasIdRoute
  '/empresas/': typeof PanelEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/solicitar': typeof SolicitarRoute
  '/admins': typeof PanelAdminsRoute
  '/auditoria': typeof PanelAuditoriaRoute
  '/facturas': typeof PanelFacturasRoute
  '/planes': typeof PanelPlanesRoute
  '/solicitudes': typeof PanelSolicitudesRoute
  '/telegram': typeof PanelTelegramRoute
  '/': typeof PanelIndexRoute
  '/empresas/$id': typeof PanelEmpresasIdRoute
  '/empresas': typeof PanelEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/login': typeof LoginRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/solicitar': typeof SolicitarRoute
  '/_panel/admins': typeof PanelAdminsRoute
  '/_panel/auditoria': typeof PanelAuditoriaRoute
  '/_panel/empresas': typeof PanelEmpresasRouteWithChildren
  '/_panel/facturas': typeof PanelFacturasRoute
  '/_panel/planes': typeof PanelPlanesRoute
  '/_panel/solicitudes': typeof PanelSolicitudesRoute
  '/_panel/telegram': typeof PanelTelegramRoute
  '/_panel/': typeof PanelIndexRoute
  '/_panel/empresas/$id': typeof PanelEmpresasIdRoute
  '/_panel/empresas/': typeof PanelEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/restablecer-password'
    | '/solicitar'
    | '/admins'
    | '/auditoria'
    | '/empresas'
    | '/facturas'
    | '/planes'
    | '/solicitudes'
    | '/telegram'
    | '/empresas/$id'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/restablecer-password'
    | '/solicitar'
    | '/admins'
    | '/auditoria'
    | '/facturas'
    | '/planes'
    | '/solicitudes'
    | '/telegram'
    | '/'
    | '/empresas/$id'
    | '/empresas'
  id:
    | '__root__'
    | '/_panel'
    | '/login'
    | '/restablecer-password'
    | '/solicitar'
    | '/_panel/admins'
    | '/_panel/auditoria'
    | '/_panel/empresas'
    | '/_panel/facturas'
    | '/_panel/planes'
    | '/_panel/solicitudes'
    | '/_panel/telegram'
    | '/_panel/'
    | '/_panel/empresas/$id'
    | '/_panel/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  LoginRoute: typeof LoginRoute
  RestablecerPasswordRoute: typeof RestablecerPasswordRoute
  SolicitarRoute: typeof SolicitarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-password': {
      id: '/restablecer-password'
      path: '/restablecer-password'
      fullPath: '/restablecer-password'
      preLoaderRoute: typeof RestablecerPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admins': {
      id: '/_panel/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof PanelAdminsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/auditoria': {
      id: '/_panel/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof PanelAuditoriaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/empresas': {
      id: '/_panel/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof PanelEmpresasRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/facturas': {
      id: '/_panel/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof PanelFacturasRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/planes': {
      id: '/_panel/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PanelPlanesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/solicitudes': {
      id: '/_panel/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof PanelSolicitudesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/telegram': {
      id: '/_panel/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof PanelTelegramRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/empresas/': {
      id: '/_panel/empresas/'
      path: '/'
      fullPath: '/empresas/'
      preLoaderRoute: typeof PanelEmpresasIndexRouteImport
      parentRoute: typeof PanelEmpresasRoute
    }
    '/_panel/empresas/$id': {
      id: '/_panel/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof PanelEmpresasIdRouteImport
      parentRoute: typeof PanelEmpresasRoute
    }
  }
}

interface PanelEmpresasRouteChildren {
  PanelEmpresasIdRoute: typeof PanelEmpresasIdRoute
  PanelEmpresasIndexRoute: typeof PanelEmpresasIndexRoute
}

const PanelEmpresasRouteChildren: PanelEmpresasRouteChildren = {
  PanelEmpresasIdRoute: PanelEmpresasIdRoute,
  PanelEmpresasIndexRoute: PanelEmpresasIndexRoute,
}

const PanelEmpresasRouteWithChildren = PanelEmpresasRoute._addFileChildren(
  PanelEmpresasRouteChildren,
)

interface PanelRouteChildren {
  PanelAdminsRoute: typeof PanelAdminsRoute
  PanelAuditoriaRoute: typeof PanelAuditoriaRoute
  PanelEmpresasRoute: typeof PanelEmpresasRouteWithChildren
  PanelFacturasRoute: typeof PanelFacturasRoute
  PanelPlanesRoute: typeof PanelPlanesRoute
  PanelSolicitudesRoute: typeof PanelSolicitudesRoute
  PanelTelegramRoute: typeof PanelTelegramRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAdminsRoute: PanelAdminsRoute,
  PanelAuditoriaRoute: PanelAuditoriaRoute,
  PanelEmpresasRoute: PanelEmpresasRouteWithChildren,
  PanelFacturasRoute: PanelFacturasRoute,
  PanelPlanesRoute: PanelPlanesRoute,
  PanelSolicitudesRoute: PanelSolicitudesRoute,
  PanelTelegramRoute: PanelTelegramRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  LoginRoute: LoginRoute,
  RestablecerPasswordRoute: RestablecerPasswordRoute,
  SolicitarRoute: SolicitarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
